name: Run Unit Tests

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  test:

    # Specifies the environment in which the workflow should run
    runs-on: ubuntu-latest

    steps:
    # Checks out your repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Sets up Python environment; specify the version of Python you are using
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    # Installs dependencies listed in your requirements.txt file (if you have one)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest

    # Runs the unit tests using pytest
    - name: Run tests
      run: pytest
